### ISSUE TITLE
Cannot closes secret chats

### ISSUE THREAD

**Issue by zink-chimaera** [yunit-io/telegram-app#11]
![image](https://cloud.githubusercontent.com/assets/19663859/25251838/f79b3d56-261a-11e7-91f5-52b8b9996944.png)

**How to reproduce:**
* Crash a secret chat
* Try to close crashed chat

**Expected**
Chat gets removed from the list

**Result**
Chat remains at the very top of the list

**Comment by dfiloni** [comment]
Closed with commit: https://github.com/yunit-io/libqtelegram-aseman-edition/commit/fef7e3a7be7c7e1424b16e246da1db33bd77ad18
