### ISSUE TITLE
Unify color scheme for status text & last message prefixes

### ISSUE THREAD

**Issue by Flohack74** [yunit-io/telegram-app#12]
![screenshot20170421_092411900](https://cloud.githubusercontent.com/assets/16186470/25267504/4cd2d2c0-2675-11e7-888c-a2ecf2edd97c.png)
The status text for media attrachment does have a different color than the prefix of the last messages for chats.

**Comment by Flohack74** [comment]
Can we do this withour breaking again localization? This is one reason why formatting should be separate from the content it formats xD

**Comment by dfiloni** [comment]
Yes, translation strings were fixed in commit: 97b13bbe4da9007fff78702db04e87f702a84848
