### ISSUE TITLE
Secret chat, secret buttons?

### ISSUE THREAD

**Issue by Jujuyeh** [yunit-io/telegram-app#13]
I get this "Waiting for user to get online..." message at the bottom on a Secret Chat because the receiver didn't logged into Telegram. But Sticker icon and Attachment icon still work even they don't show up.

**Comment by Flohack74** [comment]
Devid, can you check, I cannot see the buttons anymore, but if I touch the area on the bottom I can still open the pane with Foto, Video, Document rounded buttons. You know which one?

**Comment by Flohack74** [comment]
Ok was a wrong desktop build :)
