### ISSUE TITLE
no push notifications

### ISSUE THREAD

**Issue by flaun** [yunit-io/telegram-app#37]
Hallo,
it's nice to see some development going on.
This is my first issue posting here, so I'm sorry for making any faults.

I haven't get any push notifications from my telegram app on my ubuntu phone since one month or so.
Right know I installed the OpenStore and updated telegram (thanks for voice massages!)

But there are still no push notifications. Do you know the reasons?

Device: Meizu MX4
Telegram version: 2.4.39.6

thanks for helping me
flaun

**Comment by Flohack74** [comment]
Hello,

currently we see quite many users reporting this, even my girlfriend on E4.5 => we could not determine if it is a) device-specific b) user-specific or c) telegram-version-specific.

It seems like a random fault. Some people told us it can be fixed by deleting the UbuntuOne account, but its not a 100% fix.

I can add some debug output to give information if we could not register the notifications, maybe then I can make a version for us to see the behaviour. But most probably its not a telegram-app fault since the notifications worked until 1 or 2 months without problems.

**Comment by wagafo** [comment]
I deleted the Ubuntu One account but it did not solve it (Bq E5 device).

**Comment by flaun** [comment]
Already tried it twice. Did not helb:(
Maybe it's a problem with the ubuntu-push-helper?

**Comment by dfiloni** [comment]
Deleting the old Ubuntu One account is not enough, you'll have to register a new Ubuntu One account.

I suggest to logout from Telegram before logging out from Ubuntu One account and login again only after the new Ubuntu One account registration is completed.

**Comment by flaun** [comment]
Thanks, this worked for me. Great!
I deleted telegram, including the config and cache folder. Then I deleted my ubuntu one account and created a new one. You really have to wait until registration is completed. Then install telegram again from the openstore and push notification should work. Awesome.
Now just voice calls are left:)
thanks ubports team for keeping this project alive

**Comment by Flohack74** [comment]
As an alternative: You can also just go to Settings in Telegram and log out from your account, this will delete all relevant data. When you re-register, it might happen that you do not get a code immediately. Just close & restart Telegram, and you should receive a code. Thats another bug btw :)

**Comment by mardy** [comment]
Oops! I follow this advice (logout from the telegram settings) and now I can't even re-create the telegram account :-(
I do get the code, but when I enter it the app does not proceed, and I see this in the logs:
```
[20170529 10:18:27.016 MSK qml: ui:  error
[20170529 10:18:27.019 MSK qml: authNeeded false
[20170529 10:18:27.083 MSK authSignInError_slt "SESSION_PASSWORD_NEEDED"
[20170529 10:18:27.084 MSK qml: authNeeded true
[20170529 10:19:15.362 MSK qrc:/qml/telegram.qml:73: TypeError: Cannot read property 'registered' of null
```
Any idea on how to proceed?

**Comment by dfiloni** [comment]
You have to disable 2 factors authentication before logging in telegram-app
(it's not supported)

**Comment by mardy** [comment]
Thanks @dfiloni ! That appears to be the issue indeed. Now unfortunately I've been locked out for 24 hours because of too many attempts, but I'll try again tomorrow. :-) If you don't hear from me anymore, it means that it worked :-)
