### ISSUE TITLE
Telegram lost notifications

### ISSUE THREAD

**Issue by wagafo** [yunit-io/telegram-app#38]
As for May 20 I've lost notifications of incoming messages in Telegram. It was was working perfectly with Bq E5 legacy image, and last Telegram version from OpenStore.

**Comment by Flohack74** [comment]
Yes we know. Sad but true, more and more users failing. Im also on E5, still working but with Canonical image. We will have to be patient, either we find a reason, or, we have to live for some time w/o notifications.
